spring:
  application:
    name: chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/chat?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    hikari:
      idle-timeout: 300000
      max-lifetime: 1800000
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    output:
      ansi.enabled: always
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB
server:
  port: 8082
service:
  tale:
    url: ${TALE_URL}
  user:
    url: ${USER_URL}
openai:
  api-key: ${API_KEY}
  url: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini
  maxTokens: 1000
  temperature: 1.0
  topP: 1.0